export const ADD_INVOICE_REQUEST = 'ADD_INVOICE_REQUEST';
export const ADD_INVOICE_SUCCESS = 'ADD_INVOICE_SUCCESS';
export const ADD_INVOICE_FAILURE = 'ADD_INVOICE_FAILURE';

export const PICKUP_DATE = 'PICKUP_DATE';
export const DELIVER_DATE = 'DELIVER_DATE';

export const ADD_ORDER_REQUEST = 'ADD_ORDER_REQUEST';
export const ADD_ORDER_SUCCESS = 'ADD_ORDER_SUCCESS';
export const ADD_ORDER_FAILURE = 'ADD_ORDER_FAILURE';

export const RESET_ORDER = 'RESET_ORDER';
