export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE = 'UPDATE_USER_FAILURE';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const FORGOTTEN_REQUEST = 'FORGOTTEN_REQUEST';
export const FORGOTTEN_SUCCESS = 'FORGOTTEN_SUCCESS';
export const FORGOTTEN_FAILURE = 'FORGOTTEN_FAILURE';

export const USER_SIGNOUT = 'USER_SIGNOUT';
